version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: verbweaver-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/verbweaver.db
      - GIT_PROJECTS_ROOT=/app/projects
    volumes:
      - ./data:/app/data
      - ./projects:/app/projects
    depends_on:
      - redis
    networks:
      - verbweaver-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: verbweaver-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - verbweaver-network

  redis:
    image: redis:7-alpine
    container_name: verbweaver-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - verbweaver-network

  # Optional: PostgreSQL for production
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: verbweaver-postgres
  #   environment:
  #     - POSTGRES_USER=verbweaver
  #     - POSTGRES_PASSWORD=verbweaver_password
  #     - POSTGRES_DB=verbweaver
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - verbweaver-network

volumes:
  redis-data:
  # postgres-data:

networks:
  verbweaver-network:
    driver: bridge 